### ISSUE TITLE
Bug with DST in Period

### ISSUE THREAD

**Issue by mind-blowing** [JodaOrg/joda-time#261]
We found problem when we tried to find hours difference between two dates using CET timezone with DST. Bellow you can see tests, test **twentyFiveHoursDifference_endPlusDay will fail** and twentyFiveHoursDifference_startMinusDay will pass.

```java
public class JodaPeriodTZBugTest {

    private DateTime start = new LocalDateTime(2015, 3, 29, 1, 0).toDateTime(DateTimeZone.forID("CET"));
    private DateTime end = new LocalDateTime(2015, 3, 29, 3, 0).toDateTime(DateTimeZone.forID("CET"));

    @Test
    public void oneHourDifference() {
        assertEquals(1, new Period(start, end).toStandardDuration().toStandardHours().getHours());
    }


    @Test
    public void twentyFiveHoursDifference_endPlusDay() {
        assertEquals(25, new Period(start, end.plusDays(1)).toStandardDuration().toStandardHours().getHours());
    }

    @Test
    public void twentyFiveHoursDifference_startMinusDay() {
        assertEquals(25, new Period(start.minusDays(1), end).toStandardDuration().toStandardHours().getHours());
    }

}
```

**Comment by jodastephen** [comment]
The algorithm for `Period` has this as a side effect.

The difference is calculated by seeing how many years there are between the two dates, then how many months in the remainder, then how many days, then how many hours and so on. In this case, there is the side effect you observed.

From 2015-03-29T01:00 to 2015-03-29T03:00 is less than one day, so the algorithm only finds a difference in the hours, which does take DST into account, returning 1 hour (not 2 hours).

However, from 2015-03-29T01:00 to 2015-03-30T01:00 is more than one day. The algorithm first finds the period exceeds a day, records "1 day", and then adds 1 day to the start. This results in 2015-03-30T01:00, because adding a period of one day retains the same local time (note that in this case, only 23 actual hours were added). The algorithm then finds the period between 2015-03-30T01:00 and 2015-03-30T03:00, which is two hours (no DST effects). The result is therefore "1 day and 2 hours", which converts to a 26 hour duration.

To get the result you desire, simply use `new Duration(start, end)`.
