### ISSUE TITLE
Object build with DateTimeZone.forID() returns a different value from getID()

### ISSUE THREAD

**Issue by brad4d** [JodaOrg/joda-time#269]
Code that illustrates the problem:

    DateTimeZone montrealTz = DateTimeZone.forID("America/Montreal");
    System.out.println(String.format("montreal TZ: %s", montrealTz.getID()));

prints "montreal TZ: America/Toronto"
It should print "America/Montreal".

This is due to a recent change to the TZ database made by IANA to merge these two timezones.

I know this probably doesn't seem like a big deal, but it really is.
It is a totally reasonable assumption on a developer's part that the ID they used to create the object is the one they get back from the object. Breaking this assumption leads to subtle and hard to fix bugs in cases like.

1. Converting a Joda object to/from some other kind of DateTime object.
2. Communicating DateTimes from one system to another.
3. Comparing timezones stored as an ID string.

It isn't always possible to fix this by using Joda objects everywhere.

**Comment by jodastephen** [comment]
Joda-Time has always normalized some identifiers. However, since the TZ database maintainer has started damaging the data, this specific problem arose.

I have already implemented the necessary changes [here](https://github.com/JodaOrg/joda-time/commit/4222b61dcefc4e621f6d016e0928da0280663f87). With that commit, your sample code prints "America/Montreal". Version 2.8 will contain the change when released.
