### ISSUE TITLE
Is time zone printing broken for upcoming JDK 1.8u60?

### ISSUE THREAD

**Issue by tkowalcz** [JodaOrg/joda-time#288]
This class https://gist.github.com/tkowalcz/ac660693b852a85c14a0 will normally print:

```
date = Mon, 04 May 2015 22:00:00 GMT
```

but on 1.8u60 it will print:
```
date = Mon, 04 May 2015 22:00:00 +00:00
```

I am not familiar with intricacies of time zones and loading their definitions from JDK resources, but was able to pinpoint where Joda Time breaks: In DefaultNameProvider::getNameSet when looking up time zone definitions there are checks:

```
135: if (strings != null && strings.length == 5 && id.equals(strings[0])) {
143: if (strings != null && strings.length == 5 && id.equals(strings[0])) {
```

But on 1.8u60 call to 

```
DateTimeUtils.getDateFormatSymbols(Locale.ENGLISH).getZoneStrings();
```

will return array of arrays of seven (7!) elements.

Early release of this JDK version can be found here: https://jdk8.java.net/download.html

This will cause mayhem after the release (e.g. for us it will break all our apps talking to Amazon WebServices through their official client, as it will sen malformed requests).

Please advise.

**Comment by johnjaylward** [comment]
If you are using java 8, why are you not using the new built in date/time classes? JodaTime specifically says it is deprecated in favor of the new java8 classes.

**Comment by tkowalcz** [comment]
That is the question for maintainers of e.g. Amazon Web Services Java SDK and possibly many other libraries out there that still use Joda Time. Allowing their libraries to by run on platforms older than Java 8 is one reason that comes to mind.

**Comment by david-at-aws** [comment]
Yep, the AWS SDK still targets Java 6, and won't be dropping support for 6/7 any time real soon. I guess we could look into doing some magic to detect what version of Java we end up with at runtime and switch to use the built-in Java classes if we're on 8+? Would be nice to have a fix that anyone else using joda-time in a library could easily pick up though.

**Comment by tkowalcz** [comment]
I will try to come up with a push request this evening. If someone want's to take a stab at this the good folks at core-dev-libs pointed me (http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-June/034100.html) to a change that broke time zone printing in Joda Time: https://bugs.openjdk.java.net/browse/JDK-8076287

**Comment by jodastephen** [comment]
Please check that 31ea144fd1fc493c2f2717d61b279c6caddae4db fixes the problem.

**Comment by tkowalcz** [comment]
Yes, it does - thank you. I have run the test suite which previously failed on 1.8u60 and it works fine.

**Comment by tkowalcz** [comment]
Are you planning new release with this fixes?

**Comment by jodastephen** [comment]
Done.

**Comment by shorea** [comment]
We (the AWS SDK for Java) have still been receiving a number of customer contacts about this issue due to users pulling in older versions of Joda-Time in their Maven dependencies. A customer brought to our attention a potential fix that would eliminate the need for a version later then 2.8.1 thus making it much easier to prevent other customers from being bitten by it. I was wondering if I could get your opinion on the legitimacy of the fix and whether it could cause future problems. Basically the customer has recommended we don't use the 'z' symbol for timezone and just use a static string for GMT since we have fixed our format to that anyways. Link to customer issue below.

https://github.com/aws/aws-sdk-java/issues/514

https://github.com/aws/aws-sdk-java/issues/514
