### ISSUE TITLE
org.joda.time.Interval fails during a leap second

### ISSUE THREAD

**Issue by batrachoseps** [JodaOrg/joda-time#416]
The joda FAQ states that leap seconds are not supported, and "Most applications have no need for it..."  This is an oversimplification.  My application failed, even though it doesn't care about leap seconds.  Here is the code:

public void TimeDoSomething()
{
    DateTime start = new DateTime();
    DoSomething();
    DateTime end = new DateTime();
    print("DoSomething took %dms", new Interval(start, end).toDurationMillis());
}

Here, the Interval constructor threw IllegalArgumentException when TimeDoSomething ran during a leap second.   

I'm using joda 2.5.  Here's the stack:
Exception in thread "Thread-4" java.lang.IllegalArgumentException: The end instant must be greater or equal to the start
	at org.joda.time.base.AbstractInterval.checkInterval(AbstractInterval.java:63)
	at org.joda.time.base.BaseInterval.<init>(BaseInterval.java:94)
	at org.joda.time.Interval.<init>(Interval.java:122)

**Comment by jodastephen** [comment]
Leap seconds are always a mess, but the case you outline is fairly typical of what can happen. However, Joda-Time itself did nothing wrong, and there is no reasonable change to Joda-Time that would have helped.

In design terms, supporting leap seconds means allowing minutes to be variable length (59, 60 or 61 seconds). The idea that minutes are not 60 seconds is so unexpected to most users that they will never consider it, and thus my contention is that allowing variable length minutes results in more bugs than are caused when leap seconds do occur.

In this case, the problem arises because the underlying system clock (Java's `System.currentTimeMillis()`) returned values that went backwards. ie. it returned something like 55555 followed by 55554. This is likely driven directly off the operating system clock, which will also have seen time go backwards. The point here is that there is very little that Joda-Time could do to mitigate against this - it does not access the operating system clock.

If you want to guard against leap second issues then you have to use a leap-smeared clock, such as [Googles](https://developers.google.com/time/smear) or [UTC-SLS](https://www.cl.cam.ac.uk/~mgk25/time/utc-sls/). Such a clock could be used in Joda-Time by implementing [MillisProvider](http://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeUtils.MillisProvider.html). I don't recommend this personally, as the clock for Joda-Time would differ from the clock for those parts of the application not using Joda-Time. And anyway, implementing a clock to the precision needed will be extremely difficult.
