### ISSUE TITLE
Day off from DateTime with  Asia/Ho_Chi_Minh timezone

### ISSUE THREAD

**Issue by sob95aero** [JodaOrg/joda-time#423]
### Key information

- Joda-Time version : 2.3
- Result of `TimeZone.getDefault()` : sun.util.calendar.ZoneInfo[id="Europe/Prague",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=141,lastRule=java.util.SimpleTimeZone[id=Europe/Prague,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]

- Result of `DateTimeZone.getDefault()`: Europe/Prague

### Problem description
When trying to parse LocalDate or DateTime on server with user.timezone=Asia/Ho_Chi_Minh and year 1975 the result is one hour off the actual expected value. Due to this, all Dates are pushed one day back and Times one hour back.

I think it is due to fact that there is a unified time zone UTC+07:00:00 in whole Vietnam since 06/13/1975, but it wasn’t before.
### Test case
with -Duser.timezone=Asia/Ho_Chi_Minh

passes:
 LocalDate localDate = new LocalDate(DatatypeConverter.parseDate("1975-06-13"));
 Assert.assertEquals(1975, localDate.getYear());
 Assert.assertEquals(06, localDate.getMonthOfYear());
 Assert.assertEquals(13, localDate.getDayOfMonth());

does not pass:
 LocalDate localDate = new LocalDate(DatatypeConverter.parseDate("1975-06-12"));
 Assert.assertEquals(1975, localDate.getYear());
 Assert.assertEquals(06, localDate.getMonthOfYear());
 Assert.assertEquals(12, localDate.getDayOfMonth());
java.lang.AssertionError: 
Expected :12: 
Actual   :11

when used LocalDate.fromCalendarFields(DatatypeConverter.parseDate(value)) works fine but for DateTime and LocalTime there is no such method to convert directly from calendar fields. Also universal Etc/GMT-7 (or no timezone) works fine.

Workaround for this is to use another timezone, but this is only last chance.

Is there any glue or possible solution for this behavior/timezone for VN?

**Comment by jodastephen** [comment]
This question would probably have got a better response on Stack Overflow.

It is hard to tell exactly what is happening because you have DatatypeConverter between the parse and Joda-Time. In situations like this you should always separate out each step and provide a System.out() at each point.

Without figuring out how to test all of this, I suspect you have hit the standard problem where the JDK time-zone data differs from the data used in Joda-Time for old dates. There isn't much you can do other than workaround it, assuming you need to handle older dates. Or you could create a custom set of time-zone data that matches the JDK data (but that isn't straightforward).
