### ISSUE TITLE
Bug in MutableDateTime#parseInto with pattern yyyy-ww

### ISSUE THREAD

**Issue by apichery** [JodaOrg/joda-time#468]
### Key information

- Joda-Time version:
```
2.9.9
```

- Result of `TimeZone.getDefault()`
```
sun.util.calendar.ZoneInfo[id="Europe/Paris",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=184,lastRule=java.util.SimpleTimeZone[id=Europe/Paris,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
```

- Result of `DateTimeZone.getDefault()`
```
Europe/Paris
```

### Problem description
`MutableDateTime#parseInto` sets a wrong result when using pattern `yyyy-ww` for `2017-01`

### Test case
```
import java.text.ParseException;
import java.util.Locale;

import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.MutableDateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

public class JodaTest {

    public static void main(String[] args) throws ParseException {
        String format = "yyyy-ww";
        String date = "2017-01";

        // Parse with DateTimeFormat#parseDateTime
        DateTimeFormatter dtf = DateTimeFormat.forPattern(format).withLocale(Locale.ENGLISH).withZone(DateTimeZone.UTC);
        DateTime date1 = dtf.parseDateTime(date).toDateTime(DateTimeZone.UTC);
        System.out.println("Joda 1 => " + date1); // ==> print "2017-01-02T00:00:00.000Z"

        // Parse with DateTimeFormat#parseInto
        MutableDateTime date2 = new MutableDateTime(0, DateTimeZone.UTC);
        dtf.parseInto(date2, date, 0);
        System.out.println("Joda 2 => " + date2); // ==> #FAIL: print "2016-01-10T00:00:00.000Z"
    }
}
```

Executing this small program produces the following output:
```
Joda 1 => 2017-01-02T00:00:00.000Z
Joda 2 => 2016-01-10T00:00:00.000Z
```

### Possible diagnostic

The cause of the bug seems to be the fact that `parseInto` calls `DateTimeParserBucket#computeMillis(resetBucket, text)` with `resetFields` set to false.
Unlike `parseInto`, `parseDateTime` calls this method with `resetFields=true`

**Comment by mrjink** [comment]
Hi Arnaud,

You should use "xxxx" instead of "yyyy" when working with "ww".  Depending
on the Locale, the first of January might be either week 1 of a certain
year, or week 53 of the previous year.  In The Netherlands, for example, 1
January *2021 *is *2020*-53.

Changing the format to "xxxx-yy" yields a better result, but doesn't (yet)
explain why the days are off:

Joda 1 => 2017-01-02T00:00:00.000Z
Joda 2 => 2017-01-05T00:00:00.000Z

Gillis

**Comment by jodastephen** [comment]
This is operating by design. The `parseInto` method starts with a base `MutableDateTime` and sets each parsed field on top of that value.

* The start point is `new MutableDateTime(0, DateTimeZone.UTC)`, which gives the base as `1970-01-01T00:00Z`, which was a Thursday
* Then the weekyear is then set (assuming `xxxx` is used), retaining the day-of-week
* Then the week-of-weekyear is set, retaining the day-of-week
* The day-of-week is retained throughout, thus remains as Thursday.
* The result is thus Thursday, 2017-01-05

With the `parse` method, the algorithm is different as there is no base date, and missing fields are defaulted. ie. Thursday is not retained, but replaced by the first day of the week (Monday), yielding 2017-01-02.

**Comment by apichery** [comment]
Thanks for the explanation!
