### ISSUE TITLE
org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap')

### ISSUE THREAD

**Issue by anthony3444** [JodaOrg/joda-time#470]
Hello guys!

I have a big problem saw on an Android device (7.0), there is this crash:

```
    Fatal Exception: org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 1977-05-01T00:00:00.000 (Africa/Casablanca)
           at org.joda.time.chrono.ZonedChronology.localToUTC(ZonedChronology.java:157)
           at org.joda.time.chrono.ZonedChronology.getDateTimeMillis(ZonedChronology.java:122)
           at org.joda.time.chrono.AssembledChronology.getDateTimeMillis(AssembledChronology.java:133)
           at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:257)
           at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:198)
           at org.joda.time.DateTime.<init>(DateTime.java:323)
```
It appears when the timezone is: Africa/Casablanca (= GMT 0)

My code:

// Failed:

`    DateTime dateTime = new DateTime(year, month, 1);`

// Failed

```
    DateTime dateTime = new DateTime(year, month, 1, 0, 0, 0, 0,
      DateTimeZone.forID(TimeZone.getDefault().getID()));
```

// Failed

```
    DateTime dateTime = new DateTime(year, month, 1, 0, 0, 0, 
      DateTimeZone.forTimeZone(TimeZone.getDefault()));
```

I can't understand why it's failed with this Time zone! If I use a timezone (like GMT+1) there is no problem at all.

Thank you very much for your help!

**Comment by mrjink** [comment]
This is answered in the FAQ at
http://joda-time.sourceforge.net/faq.html#illegalinstant

Joda-Time only allows the key classes to store valid date-times. For
example, 31st February is not a valid date so it can't be stored (except in
Partial).

The same principle of valid date-times applies to daylight savings time
(DST). In many places DST is used, where the local clock moves forward by
an hour in spring and back by an hour in autumn/fall. This means that in
spring, there is a "gap" where a local time does not exist.

The error "Illegal instant due to time zone offset transition" refers to
this gap. It means that your application tried to create a date-time inside
the gap - a time that did not exist. Since Joda-Time objects must be valid,
this is not allowed.

Possible solutions may be as follows:

Use LocalDateTime, as all local date-times are valid.

When converting a LocalDate to a DateTime, then use toDateTimeAsStartOfDay()
 as this handles and manages any gaps.

When parsing, use parseLocalDateTime() if the string being parsed has no
time-zone.

Not all cases of this error have a simple solution. Hopefully this FAQ has
explained what the error means allowing you to work out what the correct
solution will be.
