### ISSUE TITLE
Period with different date but has same result

### ISSUE THREAD

**Issue by kiansenggoh** [JodaOrg/joda-time#531]
the below codes returns same result, a 5 years difference. 
should be 5Y, 5Y1D and 5Y2D?

`val date1 = org.joda.time.LocalDate(2025,2,28)
        val date2 = org.joda.time.LocalDate(2019,11,28).plusMonths(3)
        val ddd = org.joda.time.Period(date2, date1)
        println("${ddd.years} ${ddd.months} ${ddd.days}")`

`      val date1 = org.joda.time.LocalDate(2025,2,28)
        val date2 = org.joda.time.LocalDate(2019,11,29).plusMonths(3)
        val ddd = org.joda.time.Period(date2, date1)
        println("${ddd.years} ${ddd.months} ${ddd.days}")`

`val date1 = org.joda.time.LocalDate(2025,2,28)
        val date2 = org.joda.time.LocalDate(2019,11,30).plusMonths(3)
        val ddd = org.joda.time.Period(date2, date1)
        println("${ddd.years} ${ddd.months} ${ddd.days}")`

**Comment by jodastephen** [comment]
Periods involving the end of month often provide a source of "interesting" results. Joda-Time has a particular algorithm that yields the results you see. java.time.* has a different algorithm. No one algorithm is "right". Since the Joda-Time algorithm has been this way for over 15 years, its not going to change.
