### ISSUE TITLE
Does 2.12.7 fixed CVE-2024-23080 ？

### ISSUE THREAD

**Issue by hw207165** [JodaOrg/joda-time#780]
Does 2.12.7 fixed CVE-2024-23080 ？

**Comment by jodastephen** [comment]
That is the first I've heard of the CVE. It looks rubbish to me. Joda-Time, like many Java libraries, can throw NPE on null input. It is perfectly normal and not a treat IMO.

**Comment by jodastephen** [comment]
The CVE is raised by a brain-dead AI bot. https://gist.github.com/LLM4IG It is utter nonsense.

**Comment by arnovdk** [comment]
Thank you for the clarification. At our site, the problem was highlighted by Snyk, which we use in our build process.

I suspect that more folks will soon start to notice this issue... 😬

**Comment by jodastephen** [comment]
The official reference page for the Joda-Time response can be found [here](https://www.joda.org/joda-time/security.html).

**Comment by chadlwilson** [comment]
I contacted Sonatype OSSIndex (maybe others did too) and they have removed the tagging of this bad CVE against joda, so at least tools like OWASP Dependency Check will stop reporting this noise (as NIST NVD haven't tagged it to a product anyway, likely due to their resourcing problems)

Thx for your patience @jodastephen !

**Comment by karlhenselin** [comment]
It's crazy that CVE has the wrong website for joda also, linking to some store instead of joda.org.
