### ISSUE TITLE
Dates with formats starting with a leading '+' sign before the year part are getting parsed improperly

### ISSUE THREAD

**Issue by hshankar** [JodaOrg/joda-time#86]
I stumbled upon an issue where dates with leading '+' signs in front of year part were getting parsed improperly. I have described the issue in stackoverflow (http://stackoverflow.com/q/19910018/373151). I'll paste the code again here:

```
System.out.println(DateTimeFormat.forPattern("yyyyMMdd").parseDateTime("20130101"));
// 2013-01-01T00:00:00.000+05:30 (Expected) (case 1)

System.out.println(DateTimeFormat.forPattern("yyyyMMdd").parseDateTime("+20130101"));
// 20130-10-01T00:00:00.000+05:30 (??? Notice that month changed to 10 also) (case 2)

System.out.println(DateTimeFormat.forPattern("MMyyyydd").parseDateTime("01+201301"));
// 20130-01-01T00:00:00.000+05:30 (??? At least month is fine this time) (case 3)

System.out.println(DateTimeFormat.forPattern("MM-yyyy-dd").parseDateTime("01-+2013-01"));
// 2013-01-01T00:00:00.000+05:30 (I expected an error, but this parsed correctly) (case 4)
```

The year is getting parsed as 20130 instead of 2013 in cases 2 and 3.

**Comment by leadVisionary** [comment]
Was this never fixed because this isn't considered a bug? I notice this works fine:
```java
/**
     * https://github.com/JodaOrg/joda-time/issues/86
     */
    public void correctly_parses_plus_in_front_of_year() {
        // Given: a date that includes + per the spec of allowing it for 5 digit years
        final String dateTime = "+2013-01-09";
        // When: I try to parse this date
        //final DateTime result = DateTimeFormat.forPattern(pattern).parseDateTime(dateTime);
        final DateTime result = ISODateTimeFormat.dateTimeParser().parseDateTime(dateTime);
        // Then: I get back the correct year
        assertEquals(2013, result.getYear());
        // And: I get back the correct month
        assertEquals(1, result.getMonthOfYear());
        // And: I get back the correct day
        assertEquals(9, result.getDayOfMonth());
    }
```

It does seem strange to me to explicitly specify a pattern like `"yyyyMMdd"` and then expect ISO8601 dates to be accepted. 
Then again, that is specifically the pattern of http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#basicDate%28%29

Why someone would manually specify that as a pattern instead of using `ISODateTimeFormat` is strange to me. I suppose an argument could be made that an input pattern could be checked against a list of known patterns for given formats and made to be tolerant of the idiosyncrasies of that format. If that were the case, I would expect `cPatternCache` to contain some known mappings instead of starting out empty. That also seems to open up complexity in trying to keep that mapping up-to-date. 

Alternately, for semantic clarity, I would expect the ISO definition of a year (with the strange +/- Y business https://en.wikipedia.org/wiki/ISO_8601#Years) to only be applied in that case. A pattern for a given input format would be applied strictly, in which case any non-numeric characters in a string expected to conform to `"yyyyMMdd"` would trigger an `IllegalArgumentException`. 

What is correct behavior here?

**Comment by jodastephen** [comment]
Change made based on Hari Shankar's code.
