### ISSUE TITLE
Could LocalDate.getLocalMillis() be public?

### ISSUE THREAD

**Issue by amarocco-fa** [JodaOrg/joda-time#87]
As DateMidnight is now deprecated I migrated ( as suggested by the doc) to LocalDate but now I have some issue because LocalDate does not provide getMillis method.

Actually I use the suggested LocalDate.toDateTimeAtStartOfDay().getMillis() but performances are severely decreased.

If rendering .getLocalMillis() public is not possible, at least could LocalDate not be declared final so I could extend it?

Thanks

**Comment by TenHoTenHo** [comment]
Simply put, I have a LocalDateTime initiated with an instant. Why can't I retrieve the instant after creating the LocalDateTime?
LocalDateTime myDate = new LocalDateTime(-62135596800000);
long myPreviousInstant = myDate.howToGetMyInstant()?

There could be other ways to get the instant value, maybe myDate.toDate().getTime()) but I don't want to lose PERFORMANCE on such a simple thing so better way would be to make getLocalMillis public. Many developers don't look at the date as a date but also see it as a long value (ticks or milliseconds or time interval whatsoever) because the nature of a date in all languages and databases is a NUMBER

From the original java.util.Date until now the joda (java.time) Java date time is still so unnecessarily complicated but is still handicapped, otherwise slow.

**Comment by jodastephen** [comment]
You are confusing instants and local instants. The `long` millisecond value that is input in `new LocalDateTime(-62135596800000)` will be interpreted relative to UTC using the default time-zone of your JDK. This will then create a *local* instant representing the milliseconds from the *local* 1970 epoch, not from the standard UTC epoch.

In this code:

    LocalDateTime ldt = new LocalDateTime(-62135596800000L);
    System.out.println(ldt);
    System.out.println(ldt.getLocalMillis());

The local millis will only equal -62135596800000L if the JDK time-zone is UTC.

Thus the question `myDate.howToGetMyInstant()?` does not make sense. A `LocalDateTime` used the time-zone to perform a conversion and then threw the time-zone away. It is not possible to get the instant back without using the time-zone again, but you no longer know what it is.

If you want to have an object that stores an instant, use `Instant`. It allows the millisecond value you want to be retrieved easily. Or use `DateTime`, which retains the time-zone.

**Comment by jodastephen** [comment]
Closing this issue, as I have no intention of adding this method at this point. Doing so would be confusing in the API, as describing the difference between instant and local instant is hard.
